services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: stazoloto
      POSTGRES_PASSWORD: pswrd
      POSTGRES_DB: todo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: